
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database.types';

const SUPABASE_URL = "https://xuxupfweeekeuxjlxzdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1eHVwZndlZWVrZXV4amx4emRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTE3NTgsImV4cCI6MjA1OTU4Nzc1OH0.GRxLSOkCtAMM502_5nwmoSxxqarFDFuFrNOtQ4JIc_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
